### ISSUE TITLE
Gulp task not working - internal/child_process.js:274

### ISSUE THREAD

**Issue by arkroy** [hypery2k/gulp-galenframework#7]
Hi

I'm facing issues while running the gulptask. Please could you help. I'm using on Mac OSX 10.11.3  El Capitan. Please find below my Gulp task and Error on Terminal

GULPTASK ======================================================
gulp.task('test', function() {
  gulp.src(config.galen.specs).pipe(gulpGalen.check({
    url: config.galen.url,
    galenPath: gulpGalen.check({galenPath: './node_modules/.bin/galen'}),
    cwd: config.galen.test,
    htmlreport: config.galen.report
  }));
});

ERROR ON TERMINAL ======================================================
internal/child_process.js:274
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at exports.spawn (child_process.js:362:9)
    at Stream.<anonymous> (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp-galen/lib/gulp-galen.js:80:7)
    at Stream.stream.write (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp-galen/node_modules/through/index.js:26:11)
    at write (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
    at TransformState.afterTransform (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at DestroyableTransform.noop [as _transform] (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/through2.js:26:3)
    at DestroyableTransform.Transform._read (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)

**Comment by hypery2k** [comment]
Try to omit the Galenpath attribute

**Comment by arkroy** [comment]
Thanks for the suggestion, however with the galenpath, gulp pops up a different error:

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Could not start galen. Galen (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp-galenframework/lib/../node_modules/galenframework/bin/galen.cmd) not found?

**Comment by hypery2k** [comment]
Strange. Have to try it next week for myself. Can you send me your project with the gulpfile?

**Comment by arkroy** [comment]
Sure, Please find attached.
[gulpfile.js.zip](https://github.com/hypery2k/gulp-galenframework/files/179413/gulpfile.js.zip)

**Comment by arkroy** [comment]
Sure, the project is available here https://github.com/arkroy/gulp-rwd-scaffolding

**Comment by hypery2k** [comment]
I'm able to reproduce the error

**Comment by arkroy** [comment]
@hypery2k : Thanks for your help on this, however due timeline issues I have chosen to go with galen usage as described here: http://galenframework.com/docs/tutorial-using-galen-with-a-task-runner/. I wouldn't like to pursue this issue further. 

Thanks again for your time and effort to support me on this.
